[package]
name = "zed_csharp"
version = "1.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/csharp.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
fs_extra = "1.3.0"
