id = "csharp"
name = "C#"
description = "C# support."
version = "1.0.4"
schema_version = 1
authors = [
    "fminkowski <fminkowski@gmail.com>",
    "Fabian Freimueller <fabianfreimueller@gmail.com>",
]
repository = "https://github.com/zed-extensions/csharp"

[language_servers.omnisharp]
name = "OmniSharp"
language = "CSharp"

[language_servers.roslyn]
name = "Roslyn"
language = "CSharp"

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "485f0bae0274ac9114797fc10db6f7034e4086e3"
