id = "csharp"
name = "C#"
description = "C# support."
version = "1.0.1"
schema_version = 1
authors = [
    "fminkowski <fminkowski@gmail.com>",
    "Fabian Freimueller <fabianfreimueller@gmail.com>",
]
repository = "https://github.com/zed-extensions/csharp"

[language_servers.omnisharp]
name = "OmniSharp"
language = "CSharp"

[language_servers.roslyn]
name = "Roslyn"
language = "CSharp"

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "dd5e59721a5f8dae34604060833902b882023aaf"

[debug_adapters.netcoredbg]
schema_path = "debug_adapter_schemas/netcoredbg.json"

[debug_locators.csharp-test-runner]

# Used to run `csharp-language-server --download` after an update
[[capabilities]]
kind = "process:exec"
command = "*"
args = ["--download"]

[[capabilities]]
kind = "download_file"
host = "github.com"
path = ["qwadrox", "netcoredbg", "**"]

[[capabilities]]
kind = "download_file"
host = "objects.githubusercontent.com"
path = ["**"]
